### ISSUE TITLE
very cool

### ISSUE THREAD

**Issue by notperry1234567890** [olliem5/beginning-of-time#1]
🆒

**Comment by moomooooo** [comment]
i kinda disagree with this but whatever.

**Comment by olliem5** [comment]
wow ur so cringe omg

**Comment by notperry1234567890** [comment]
> wow ur so cringe omg

LARP

**Comment by olliem5** [comment]
> 
> 
> > wow ur so cringe omg
> 
> have a git history from 1969 then talk to me
